---

- name: cyberloop.local workstation configuration
  hosts: win_workstation

  roles:
    - commonwkstn

  tasks:

  - name: Set configure dns
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - "{{ dc_ip }}"
      log_path: C:\dns_log.txt

  - name: Ensure directory structure for public share exists
    win_file:
      path: C:\shares\public
      state: directory

  - name: Ensure public share exists
    win_share:
      name: public
      description: Basic RW share for all domain users
      path: C:\shares\public
      list: yes
      full: Administrators
      change: Users

  - name: add windows 10 workstation to cyberloop.local
    win_domain_membership:
      dns_domain_name: cyberloop.local
      domain_admin_user: Administrator@cyberloop.local
      domain_admin_password: "{{ Administrator_pass }}"
      state: domain
    register: domain_state

  - name: reboot workstation if needed
    win_reboot:
    when: domain_state.reboot_required

  - name: Ensure that bob@cyberloop.local is present as local administrator
    win_group_membership:
      name: Administrators
      Members:
        - bob@CYBERLOOP.local
      state: present

