# Adjust your timezone
- name: Set timezone to Europe/Rome
  timezone:
    name: Europe/Rome
  become: yes

- name: Add multiverse repository 
  shell: apt-add-repository multiverse -y
  args:
    executable: /bin/bash
  become: yes

- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: yes
  become: yes

- name: Install important tools
  apt: 
    name: ['krb5-user', 'chrony', 'python3-pip', 'realmd', 'sssd', 'sssd-tools', 'libnss-sss', 'libpam-sss', 'adcli', 'samba-common-bin', 'oddjob', 'oddjob-mkhomedir', 'packagekit']
    state: present
  become: yes

- pip:
    name: pexpect
  become: yes
